import type { Metadata } from "next";
import { Josefin_Slab, Mulish } from "next/font/google";
import "./globals.css";

const josefinSlab = Josefin_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Magic Rainbow",
  description: "Generated by Magic Rainbow",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefinSlab} ${mulish} antialiased`}>{children}</body>
    </html>
  );
}
